### ISSUE TITLE
Installation fails: Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by Leamsi9** [vyuldashev/laravel-openapi#33]
When running composer require, it hits this error on api.php line 8. Can't install. Don't have this issue with composer require on any other packages I just tested. 

```
In api.php line 8:
                                           
  Invalid argument supplied for foreach()  
                                           

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by vyuldashev** [comment]
Which version?

**Comment by Leamsi9** [comment]
I presume v1.0.3. It happens on `composer require vyuldashev/laravel-openapi` which I presume installs the latest version?

**Comment by vyuldashev** [comment]
I just tried with a clean installation of Laravel and I see no errors. Do you try to install it to Laravel or Lumen?

**Comment by hendrikbl** [comment]
I was getting the same error when I first tried installing into my existing Laravel 8 project.

This happens if the config was cached using `php artisan config:cache`. After that every call to new config values, inlcluding `config('openapi.collections')` will return `null`, thus the error.

The solution is simple: Just run `php artisan config:clear` and installation will run smoothly. At least it did for me.
